{
    "auxdata_path" : "/datalake/watcal/auxdata",
    "data_root" : '/work/ALT/swot/aval/OBS2CO/git/grs2/grsdata',
    "tmp_dir" : '/tmp',
    "cams_folder" : '/datalake/watcal/ECMWF/CAMS',
    "chain_version" : 1.0,
    "product_counter" : 003,
    "log" : "info",                                  # niveau de log : info, debug, warning, error
    "output_dir": "/datalake/watcal/OUTPUT_TEST",    # répertoire où seront ecrits les produits générés
    "file_tbp": "",
    "outfile": "", 
    "altitude": "", 
    "aerosol": "cams_forecast", 
    "aeronet_file": "no", 
    "resolution": "20", 
    "aot550": "aot550", 
    "angstrom": "0.5", 
    "unzip": "False",
    "untar": "False", 
    "startrow": "0", 
    "logfile": "/tmp/logger.txt"

}
