{
    "altitude": 0,
    "aeronet_file": "no", 
    "resolution": 20, 
    "aot550": 0.1, 
    "angstrom": 0.5, 
    "startrow": 0, 
    "dem": True,
    "memory_safe" : False, 
    "angleonly": False,
    "grs_a": False, 
    "output": "Rrs",
}
