name: grs
channels:
  - conda-forge
  - default
dependencies:
  - gdal
  - xarray
  - rioxarray
  - pyproj
  - pip>=20.1  # pip is needed as dependency
  - pip:
    - myst-nb
    - myst-parser
    - ipython
    - sphinx-book-theme
    - sphinx-copybutton
    - linkify-it-py
    - geopandas
    - jupyter
    - cartopy
    - importlib_resources
    - cdsapi>=0.6.1
    - GRSdriver >= 1.0.3
    - xmltodict
    - docopt
    - netCDF4
    - numba
    - numpy
    - pandas>=2.0.3
    - s2cloudless>=1.7.1
    - eoreader
    - pystac
    - holoviews
    - datashader
    - bokeh