name: grs
channels:
  - conda-forge
  - default
dependencies:
  - gdal
  - pip>=20.1  # pip is needed as dependency
  - pip:
    - myst-nb
    - myst-parser
    - ipython
    - sphinx-book-theme
    - sphinx-copybutton
    - linkify-it-py
    - geopandas
    - jupyter
    - cartopy
