name: Pipeline CI

on:
  push:
    branches:
      - feature/dev-ci
  pull_request:
    branches:
      - feature/dev-ci

jobs:
  init:
   runs-on: ubuntu-latest
   container:
      image: python:3.11.14-bookworm
   steps:
     - uses: actions/checkout@v4
     - run: |
         python -m venv python_env
         . python_env/bin/activate
         python -m pip install --upgrade pip
         python -m pip install -r requirements.txt --no-cache-dir --force-reinstall
     - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
         name: python-env
         path: python_env/ 
         retention-days: 1

  build:
    needs: init
    runs-on: ubuntu-latest
    container:
      image: ubi9/podman:9.5
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-env
          path: .
      - run: |
          ls
          mkdir -p certs
  
   
  
