name: Pipeline CI

on:
  push:
    branches:
      - feature/dev-ci
    tags:
      - '*'
  pull_request:
    branches:
      - feature/dev-ci

env:
  TARGET_REPO: "obs2co-docker"
  SUFFIX_DOCKER_IMAGE: "grs"

jobs:



# =============================================================================
# test
# =============================================================================
  python-tests:
   runs-on: ubuntu-latest
   container:
     image: openeuler/slurm:25.11.6.1-oe2403sp3
   steps:
      - uses: actions/checkout@v4
      - name: Tests
        run: |
         python3 -m venv python_env
         . python_env/bin/activate
         python3 -m pip install --upgrade pip
         python3 -m pip install -r requirements.txt --no-cache-dir --force-reinstall
          echo "TODO"

# =============================================================================
# package — Build & Push
# =============================================================================
  podman-build:
    needs: python-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          export DOCKER_IMAGE_NAME="${TARGET_REPO}/${SUFFIX_DOCKER_IMAGE}"
          echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}"
          export VERSION_GRS=$(grep version pyproject.toml | cut -d '"' -f 2)
          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
            echo "Tag : $GITHUB_REF_NAME"
            export VERSION_GRS=${GITHUB_REF_NAME};
          fi
          echo "Version GRS -> ${VERSION_GRS}"
          
          podman build \
            --network=host \
            --build-arg IMAGE_SOURCE="" \
            --build-arg no_proxy=cnes.fr \
            --file Dockerfile \
            --tag "${DOCKER_IMAGE_NAME}:${VERSION_GRS}" \
            --tag "${DOCKER_IMAGE_NAME}:latest"

          if [ "$GITHUB_REF_TYPE" = "tag" ]; then

            echo "${{ secrets.DOCKERHUB_TOKEN }}" | podman login docker.io \
                -u "${{ secrets.DOCKERHUB_LOGIN }}" \
                --password-stdin
                
            echo "Tag de l'image pour docker.io"
            echo "podman tag ${DOCKER_IMAGE_NAME}:${VERSION_GRS} docker.io/${{ secrets.DOCKERHUB_LOGIN }}/${DOCKER_IMAGE_NAME}:${VERSION_GRS}"
             
            podman tag ${DOCKER_IMAGE_NAME}:${VERSION_GRS} docker.io/${{ secrets.DOCKERHUB_LOGIN }}/${DOCKER_IMAGE_NAME}:${VERSION_GRS}
            podman tag ${DOCKER_IMAGE_NAME}:latest docker.io/${{ secrets.DOCKERHUB_LOGIN }}/${DOCKER_IMAGE_NAME}:latest
            
            echo "Publication vers docker.io"
            podman push docker.io/${{ secrets.DOCKERHUB_LOGIN }}/${DOCKER_IMAGE_NAME}:${GITHUB_REF_NAME}
          fi


# =============================================================================
# quality
# =============================================================================
  sonar:
    needs: podman-build
    runs-on: ubuntu-latest
    container:
     image: sonarsource/sonar-scanner-cli:11.3.1.1910_7.1.0
    steps:
      - uses: actions/checkout@v4
      - name: Scan SonarCloud
        run: |
          echo "host.url=${{ vars.SONAR_HOST_URL }}"
          echo "host.url=${{ vars.SONAR_ORGANIZATION }}"
          echo "host.url=${{ vars.SONAR_PROJECT_KEY }}"
          echo "host.url=${{ vars.SONAR_PROJECT_NAME }}"
          echo "host.url=${{ secrets.SONAR_TOKEN }}"
            
          sonar-scanner -Dsonar.qualitygate.wait=true \
            -Dsonar.scanner.truststorePath=/tmp/writable_keystore \
            -Dsonar.scanner.truststorePassword=changeit \
            -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} \
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} \
            -Dsonar.projectName="${{ vars.SONAR_PROJECT_NAME }}" \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
    

      

      
